### ISSUE TITLE
Setup Lane Following

### ISSUE THREAD

**Issue by garethellis0** [UBC-Snowbots/IARRC-2017#3]
- Once image stitching is complete, we will need to follow the white lines (turning as appropriate)
- We probably want to use this: https://github.com/jdorweiler/lane-detection

**Comment by garethellis0** [comment]
@raadkhan - does the above description make things pretty clear? It's pretty short, so let me know if you want me to elaborate or provide detail. We should probably meet tomorrow either way.

**Comment by raadkhan** [comment]
initial creation done, moving on to testing.
